=== gustavovieirasouza78/Study/XML/src/venda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="venda">
		<complexType>
			<sequence>
				<element name="formaDePagamento" type="string" />
				<element name="endereco" type="string" />
				<element name="produtos">
					<complexType>
						<sequence>
							<element name="produto" maxOccurs="500">
								<complexType>
									<sequence>
										<element name="nome" type="string"/>
										<element name="preco" type="double"/>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>				
			</sequence>
			<attribute name="moeda" type="string"/>
		</complexType>
	</element>
	
</schema>

=== gustavovieirasouza78/Study/XML/src/vendas.xml
<?xml version="1.0" encoding="UTF-8"?>
<venda moeda="real" xsi:noNamespaceSchemaLocation="venda.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<formaDePagamento>Cart√£o</formaDePagamento>
	<endereco>Rua Aclimacao</endereco>
	<produtos>
		<produto>
			<nome>Livro de XML</nome>
			<preco>29.90</preco>
		</produto>
		<produto>
			<nome>Livro de OO em Java</nome>
			<preco>29.90</preco>
		</produto>
	</produtos>
</venda>
